services:
  redis-stack:
    image: redis/redis-stack:latest
    restart: unless-stopped
    ports:
      - "8001:8001"
      - "6379:6379"
    networks:
      - db_net

  chromadb:
    image: chromadb/chroma:0.6.3
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=true
      - ANONYMIZED_TELEMETRY=false
    volumes:
      - ./chroma_data:/chroma/chroma
    networks:
      - db_net

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: minha_base
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_net

  postgres-web:
    image: sosedoff/pgweb:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://usuario:senha@postgres:5432/minha_base?sslmode=disable
    networks:
      - db_net
    depends_on:
      - postgres

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - db_net
    restart: unless-stopped
    entrypoint: >
      sh -c "
      ollama serve &
      sleep 2 &&
      ollama pull llama3:8b-instruct-q4_0 &&
      ollama pull mistral:7b-instruct-v0.2-q4_0 &&
      ollama pull phi3:medium-4k-instruct-q4_0 &&
      ollama pull codegemma:7b-instruct-q4_0
      "

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "8383:8080"
    environment:
      - DEFAULT_USER=admin@gmail.com
      - DEFAULT_PASSWORD=221232
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui-data:/app/backend/data
    networks:
      - db_net
    depends_on:
      - ollama

  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./chroma_data:/app/chroma_data
      - ./logs:/app/logs
    environment:
      - CHROMA_DB_HOST=chromadb
      - CHROMA_DB_PORT=8000
      - POSTGRES_DB=minha_base
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis-stack
      - REDIS_PORT=6379
    networks:
      - db_net
    depends_on:
      - chromadb
      - postgres
      - redis-stack
    restart: unless-stopped

volumes:
  open-webui-data:
  ollama_data:
  postgres_data:
  chroma_data:
  redisinsight_data:

networks:
  db_net:
    name: db_net